# The URL the site will be built for
base_url = "https://juanbri.es"

# The site title and description; used in feeds by default.
title = "Juan Brieva's Website"
description = "My personal website"

# The default language; used in feeds.
default_language = "en"

# When set to "true", the Sass files in the `sass` directory in the site root are compiled.
# Sass files in theme directories are always compiled.
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# The default author for pages
author = "Juan Brieva"


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# The theme to use for code highlighting.
# See below for list of allowed values.
highlight_theme = "dracula"

# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => ğŸ˜„)
render_emoji = true

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# Whether smart punctuation is enabled (changing quotes, dashes, dots in their typographic form)
# For example, `...` into `â€¦`, `"quote"` into `â€œcurlyâ€` etc
smart_punctuation = false


[languages.es]

[extra]
# Custom variables here

# Pages included in the navBar
nav = [
    { path = "/", label = "home" },
    { path = "/blog/", label = "blog" },
    { path = "/projects/", label = "projects" },
    { path = "/about/", label = "about" },
]
